<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Nullable>disable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ReportDesk.Core/ReportDesk.Core.csproj" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
    <Compile Include="../../src/ReportDesk.Web/Sync/*.cs" Link="Sync/%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
