const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { once } = require('node:events');
const { Bridge } = require('../../src/ReportDesk.Desktop/bridge.cjs');
const root = path.resolve(__dirname, '../..');
const { _electron: electron } = require(path.join(root, 'src/ReportDesk.Desktop/node_modules/playwright'));
const run = path.join(root, 'artifacts/verification/desktop', 'recheck-' + Date.now());
const data = path.join(run, 'local', 'ReportDesk'), config = path.join(run, 'config');
fs.mkdirSync(data, { recursive: true }); fs.mkdirSync(config, { recursive: true });
const packed = process.argv[2] && path.resolve(process.argv[2]);
if (packed) assert.ok(packed.startsWith(path.join(root, 'artifacts/verification/desktop') + path.sep));
const host = packed ? path.join(path.dirname(packed), 'resources/host/ReportDesk.Host.exe') : path.join(root, 'artifacts/host/ReportDesk.Host.exe');
const baseline = path.join(root, 'artifacts/verification/desktop/update-1789117670762/installation with spaces/resources/host/ReportDesk.Host.exe');
const source = 'E:/sql/yljhis/LIB/LIB/Config/Xml/(病案)危重抢救患者明细查询设置.xml';
const original = fs.readFileSync(source), hash = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
const sample = path.join(run, '(病案)危重抢救患者明细查询设置.xml'); fs.writeFileSync(sample, original);
const xml = flags => `<ReportQueryInfo><QueryDataSource><QueryDataSource><Name>main</Name><Sql>select 1 from dual</Sql><SqlType>MainReportUsing</SqlType></QueryDataSource><QueryDataSource><Name>detail</Name>${flags}<Sql>select :x from dual</Sql><SqlType>DetailReportUsing</SqlType></QueryDataSource></QueryDataSource></ReportQueryInfo>`;
let b, app;
async function stop() { if (b) { const done = once(b.process, 'exit'); b.close(); await done; b = null; } }
(async () => {
  b = new Bridge(baseline, data, config, true, () => {}, () => {});
  const old = (await b.call('import', { path: sample })).reports.find(r => r.path === sample);
  assert.equal(old.status, '待适配');
  await b.call('favorite', { reportId: old.id, favorite: true });
  await b.call('metadata', { reportId: old.id, category: '测试保留', aliases: '', notes: 'keep', verified: false });
  await stop();
  b = new Bridge(host, data, config, true, () => {}, () => {});
  assert.equal((await b.call('select', { reportId: old.id })).selectedIssues.length, 1);
  const refreshed = await b.call('recheck'); assert.equal(refreshed.checkedCount, 1); assert.equal(refreshed.errors.length, 0);
  const detail = await b.call('select', { reportId: old.id });
  assert.equal(detail.selectedIssues.length, 0); assert.match(detail.adaptation, /已修正导入副本/);
  assert.equal(detail.favorite, true); assert.equal(detail.notes, 'keep'); assert.equal(detail.category, '测试保留');
  assert.match((await b.call('definition', { reportId: old.id })).text, /wm_concat\(类型\)/);
  assert.equal(hash(fs.readFileSync(sample)), hash(original)); assert.equal(hash(fs.readFileSync(source)), hash(original));
  // Unknown revisions must not inherit a punctuation waiver.
  const unknown = path.join(run, 'unknown.xml'); fs.writeFileSync(unknown, Buffer.concat([original, Buffer.from('\n')]));
  const un = (await b.call('import', { path: unknown })).reports.find(r => r.path === unknown);
  assert.match(un.issues.join('\n'), /全角括号/); assert.match(un.issues.join('\n'), /第 \d+ 行，第 \d+ 列/);
  const independent = path.join(run, 'independent.xml'); fs.writeFileSync(independent, xml(''));
  const ind = (await b.call('import', { path: independent })).reports.find(r => r.path === independent);
  assert.match(ind.status, /部分可试查/);
  await assert.rejects(b.call('query', { reportId: ind.id, source: 0 }), /禁止真实数据库/);
  await assert.rejects(b.call('query', { reportId: ind.id, source: 1 }), /待适配/);
  const shared = path.join(run, 'shared.xml'); fs.writeFileSync(shared, xml('<IsCross>true</IsCross>'));
  const dep = (await b.call('import', { path: shared })).reports.find(r => r.path === shared);
  await assert.rejects(b.call('query', { reportId: dep.id, source: 0 }), /待适配/);
  fs.renameSync(unknown, unknown + '.unavailable');
  assert.equal((await b.call('recheck')).errors.length, 1);
  // Restore baseline issue metadata to prove the actual UI button refreshes it.
  await stop();
  const catalog = JSON.parse(fs.readFileSync(path.join(data, 'catalog.json'), 'utf8'));
  const entry = catalog.Reports.find(r => r.Id === old.id); entry.ScopedValidation = false; entry.Issues = ['旧版待适配'];
  fs.writeFileSync(path.join(data, 'catalog.json'), JSON.stringify(catalog));
  const env = { ...process.env, REPORTDESK_TEST: '1', REPORTDESK_TEST_DATA: data, REPORTDESK_TEST_CONFIG: config };
  delete env.ELECTRON_RUN_AS_NODE;
  if (packed) { delete env.REPORTDESK_TEST; delete env.REPORTDESK_TEST_DATA; delete env.REPORTDESK_TEST_CONFIG; env.LOCALAPPDATA = path.join(run, 'local'); }
  app = await electron.launch(packed ? { executablePath: packed, env } : { args: [path.join(root, 'src/ReportDesk.Desktop')], env });
  const page = await app.firstWindow(); page.setDefaultTimeout(30000);
  await page.waitForFunction(() => document.querySelector('#operation-status').textContent === '准备就绪。');
  await page.fill('#report-search', '危重抢救');
  await page.waitForFunction(() => document.querySelector('#report-title').textContent.includes('危重抢救'));
  assert.equal(await page.locator('#query').isDisabled(), true);
  await page.click('#recheck'); await page.waitForFunction(() => document.querySelector('#notice-title').textContent === '重新检查完成');
  assert.match(await page.locator('#notice-body').innerText(), /未更新 1 张/);
  await page.locator('#notice [data-close]').click();
  assert.equal(await page.locator('#query').isDisabled(), false); assert.match(await page.locator('#issues').innerText(), /已修正导入副本/);
  assert.equal(await page.locator('#progress').evaluate(el => getComputedStyle(el).height), '10px');
  await page.screenshot({ path: path.join(run, 'rescue-ready.png') });
  await page.fill('#report-search', 'independent'); await page.waitForFunction(() => document.querySelector('#report-title').textContent === 'independent');
  assert.equal(await page.locator('#query').isDisabled(), false);
  await page.selectOption('#source', '1'); await page.waitForFunction(() => document.querySelector('#issues').textContent.includes('原生绑定变量'));
  assert.equal(await page.locator('#query').isDisabled(), true);
  await page.screenshot({ path: path.join(run, 'source-specific.png') });
  await app.close(); app = null;
  fs.writeFileSync(path.join(run, 'PASS.txt'), 'PASS legacy recheck, exact correction/source preservation, unknown revision rejection, independent source guard, shared dependency guard, missing source retention, metadata preservation, actual Electron UI and original progress bar. Oracle NOT RUN.\n');
  console.log('PASS ' + run);
})().catch(async e => { console.error(e); await stop(); if (app) await app.close(); process.exitCode = 1; });
