<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><PlatformTarget>x64</PlatformTarget><AssemblyName>ReportDesk.Host</AssemblyName></PropertyGroup>
  <ItemGroup><ProjectReference Include="../ReportDesk.Core/ReportDesk.Core.csproj" /><Reference Include="System.Web.Extensions" /></ItemGroup>
</Project>
