<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType><PlatformTarget>x64</PlatformTarget>
    <AssemblyName>ReportDesk.Web</AssemblyName>
    <DefineConstants>$(DefineConstants);REPORTDESK_WEB</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ReportDesk.Core/ReportDesk.Core.csproj" />
    <Reference Include="System.Web" /><Reference Include="System.Web.Extensions" />
    <Reference Include="System.Configuration" /><Reference Include="System.Data" />
    <Reference Include="System.IO.Compression" /><Reference Include="System.IO.Compression.FileSystem" />
    <Compile Include="../ReportDesk.Host/*.cs" Link="SharedHost/%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
